language: java
sudo: enabled
jdk: openjdk10

services:
  - docker

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"  

before_deploy:
  - docker build -t wcapture:$BRANCH .
  - docker images

deploy:
  provider: script
  script: docker images
  on:
    all_branches: true
    