language: java
sudo: enabled
jdk: openjdk10

services:
  - docker

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"  

before_deploy:
  - "sudo docker build -t wcapture:$BRANCH ."
  - sudo docker images

deploy:
  provider: script
  script: "sudo docker images"
  on:
    all_branches: true
    