language: java
sudo: enabled
jdk: openjdk11

addons:
  hosts:
    - wcapturedb
    - rabbitmq-host
  apt:
    packages:
      - mysql-client
      - rabbitmq-server
services:
  - docker

before_install:
  - docker run -d --name mysql -p 127.0.0.1:3306:3306 -e MYSQL_ROOT_PASSWORD=r00t mysql:8.0.18
  - ./scripts/bash/init

install: /bin/true

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export IMAGE_TAG=$(echo $BRANCH | tr / _)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH, TAG=$IMAGE_TAG"
  - mvn clean verify

before_deploy:
  - docker build -t $REGISTRY_NAME/wcapture:$IMAGE_TAG -f docker/Dockerfile .
  - docker images
  - echo "$REGISTRY_PWD" | docker login -u "$REGISTRY_USER" --password-stdin $REGISTRY_NAME

deploy:
  provider: script
  script: docker push $REGISTRY_NAME/wcapture:$IMAGE_TAG
  on:
    all_branches: true
