language: java
sudo: enabled
jdk: openjdk10

addons:
  hosts:
    - mysql-host
    - phantom-host
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

services:
  - docker

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('r00t') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pr00t
  - sudo service mysql restart
  - docker run -d --name phantomjs -p 127.0.0.1:8910:8910 wernight/phantomjs phantomjs --webdriver=8910
  - ./scripts/bash/init

install: /bin/true

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export IMAGE_TAG=$(echo $BRANCH | tr / _)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH, TAG=$IMAGE_TAG"
  - mvn clean package failsafe:integration-test

before_deploy:
  - docker build -t $REGISTRY_NAME/wcapture:$IMAGE_TAG -f docker/Dockerfile .
  - docker images
  - echo "$REGISTRY_PWD" | docker login -u "$REGISTRY_USER" --password-stdin $REGISTRY_NAME

deploy:
  provider: script
  script: docker push $REGISTRY_NAME/wcapture:$IMAGE_TAG
  on:
    all_branches: true
