version: '3'

services:

  mysql:
    image: mysql:8.0.18
    ports:
      - 3306:3306
    container_name: mysql-host
    environment:
      MYSQL_ROOT_PASSWORD: r00t

  phantomjs:
    image: wernight/phantomjs
    ports:
      - 8910:8910
    container_name: phantom-host
    command: phantomjs --webdriver=8910
