version: '2'
services:
  mysql:
    image: mysql:5.7.21
    container_name: mysql-host
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
    ports:
      - "3306:3306"
  phantomjs:
    image: wernight/phantomjs
    ports:
      - "8910:8910"
    container_name: phantom-host
    command: phantomjs --webdriver=8910
    restart: unless-stopped
