version: '2'
services:
  wcapture:
    image: {{image.name}}
    ports:
      - "8080"
    external_links:
      - "mysql:mysql-host"
      - "phantom:phantom-host"
#   environment:
#   volumes:
#     - "./captures:/opt/wcapture/captures"
    restart: unless-stopped
